spring.application.name=ElectricitySystem
spring.thymeleaf.check-template-location=false

spring.datasource.driver-class-name=dm.jdbc.driver.DmDriver
spring.datasource.url=jdbc:dm://192.168.10.135:5236?charset=UTF-8
spring.datasource.username=SYSDBA
spring.datasource.password=Dameng123

spring.jpa.database-platform=org.hibernate.dialect.DmDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.DmDialect

# JWT 配置 128位置 Base64编码
jwt.secret=NjEwNjAyNDE3NjY1NzUwNjMxNjQ1ODE4ODEyNTYwNjQwMjU4MzE3NDUzNjUyNDM4ODIxNDE2MDQzMTMzMjY2MjM3MTUzMjc0NDQ3MjQ0MDY1NzUyNTY4NzMzMTUyNTU1NDE4MDg0ODczODU2NjM3MjY1MTgyMTE4MDYzNDE0MzM=
jwt.expiration=86400000

# --- 二、MyBatis 基本配置 ---
# 扫描 Mapper 接口所在包（如果你在主类上没加 @MapperScan）
mybatis.mapper-locations=classpath:/mappers/*.xml
# 实体别名（Alias）所在包，XML/注解里就可以直接用类名
mybatis.type-aliases-package=com.yjq.electricitysystem.entity

# 驼峰映射：数据库的 snake_case 列名 会自动映射到 Java 的 camelCase 属性，也就是下划线转驼峰
mybatis.configuration.map-underscore-to-camel-case=true
# 打印SQL
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper 相关配置：
# 达梦数据库方言
pagehelper.helperDialect=dm
# 页码<=0时查询第一页，页码>总页数时查询最后一页
pagehelper.reasonable=true
# 通过方法参数来传递分页参数
pagehelper.supportMethodsArguments=true
# 统计查询的参数
pagehelper.params=count=countSql

server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8
